med_registration/med_registration_project/med_registration_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('registration_app.urls', namespace='registration')),
]

med_registration/med_registration_project/registration_app/urls.py
from django.conf.urls import url
from . import views


app_name = 'registration'

urlpatterns = [
    url(r'^$', views.user_login, name='user_login'),
    url(r'^registration/$', views.user_register, name='user_register'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^doctors/$', views.doctors, name='doctors'),
    url(r'^(?P<id>\d+)/$', views.schedule, name='schedule'),
    url(r'^(?P<id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/$', views.record, name='record_list'),
]

med_registration/med_registration_project/registration_app/models.py
from django.db import models


class Specialty(models.Model):
    title = models.CharField(max_length=50, verbose_name='Специальность')

    class Meta:
        verbose_name = 'Специальность'
        verbose_name_plural = 'Специальности'

    def __str__(self):
        return self.title


class Doctors(models.Model):
    specialty = models.ForeignKey(Specialty, verbose_name='Специальность', on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50, verbose_name='ФИО')

    class Meta:
        verbose_name = 'Врач'
        verbose_name_plural = 'Врачи'

    def __str__(self):
        return self.full_name


class Schedule(models.Model):
    specialty = models.ForeignKey(Specialty, verbose_name='Специальность', on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctors, verbose_name='Врач', on_delete=models.CASCADE)
    client = models.CharField(max_length=255, verbose_name='Посетитель')
    pub_date = models.DateTimeField(max_length=15, verbose_name='Дата', blank='True')

    def __str__(self):
        return self.client

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'График'

med_registration/med_registration_project/registration_app/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password')

med_registration/med_registration_project/registration_app/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse
from .forms import UserForm
from .models import Doctors, Specialty, Schedule

from calendar import Calendar
from datetime import time, datetime as dt


def get_datetime(args):

    # Блок получающий актуальные даты текущего месяца
    NOW = dt.today()
    dates = Calendar(0).itermonthdates(NOW.year, NOW.month)
    actual_dates = [date for date in dates if not (dt.isoweekday(date) in [6, 7]) and date >= NOW.date()]

    WORK_DATES = []
    WORK_TIME = [time(hour, 0) for hour in range(9, 19)]
    for actual_date in actual_dates:
        for work_hour in WORK_TIME:
            WORK_DATES.append(dt.combine(actual_date, work_hour))

    # Извлекаем из queryset данные date, time. Не понимаю почему, но через for не хочет работать (хотя иногда работает),
    # требует целочисленный индекс у arg
    qs_dates = [dt.combine(dt.date(arg['pub_date']), dt.time(arg['pub_date'])) for arg in args]

    # Получаем список свободных дней и часов для записи к врачу
    [WORK_DATES.remove(work_date) for work_date in WORK_DATES if work_date in qs_dates]

    # Сортируем список рабочих дат по возрастанию
    work_days = sorted({dt.date(work_date) for work_date in WORK_DATES})

    # Создаем словарь дата: [время] свободных для записи к врачу
    DATES_DICT = {}
    time_list = []
    for work_day in work_days:
        for work_date in WORK_DATES:
            if work_day == dt.date(work_date):
                time_list.append(dt.time(work_date).hour)
        DATES_DICT[work_day] = time_list
        time_list = []

    return {'work_dates': work_days, 'dates_dict': DATES_DICT}


def schedule(request, id):
    if request.user.is_authenticated():
        current_date = dt.combine(dt.today().date(), time(0, 0))
        schedule_query = Schedule.objects.filter(doctor__id=id, pub_date__gte=current_date).order_by('pub_date').values()
        datetime_list = get_datetime(schedule_query)
        context = {
            'work_dates': datetime_list['work_dates'],
            'dates_dict': datetime_list['dates_dict'],
            'doctor': get_object_or_404(Doctors, id=id),
            'btn_title': 'Выйти',
            'url_btn': reverse('registration:user_logout'),
            'title_page': 'Расписание приема посетителей',
        }
        return render(request, 'registration_app/schedule.html', context)
    else:
        return redirect('registration:user_login')


def record(request, id, year, month, day, hour):
    if request.user.is_authenticated():
        str_date = '{}/{}/{} {}:00'.format(year, month, day, hour)
        format_str = "%Y/%m/%d %H:%M"
        context = {
            'client': '{} {}'.format(request.user.first_name, request.user.last_name),
            'doctor': get_object_or_404(Doctors, id=id),
            'record_date': dt.strptime(str_date, format_str).date(),
            'record_time': dt.strptime(str_date, format_str).time(),
            'btn_title': 'Выйти',
            'url_btn': reverse('registration:user_logout'),
            'title_page': 'Лист записи',
        }
        record_list = Schedule(client=context['client'],
                          pub_date=dt.combine(context['record_date'], context['record_time']),
                          doctor=context['doctor'],
                          specialty=context['doctor'].specialty
                          )
        record_list.save()
        return render(request, 'registration_app/record.html', context)
    else:
        return redirect('registration:user_login')


def doctors(request):
    if request.user.is_authenticated():
        context = {
            'doctors': Doctors.objects.all().order_by('specialty'),
            'specialty': Specialty.objects.all().order_by('id'),
            'btn_title': 'Выйти',
            'url_btn': reverse('registration:user_logout'),
            'title_page': 'Специалисты клиники',
        }
        return render(request, 'registration_app/doctors.html', context)
    return redirect('registration:user_login')


def user_login(request):
    context = {}
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        username = user_form['username'].data
        password = user_form['password'].data
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('registration:doctors'))
            else:
                context['error'] = 'Данный аккаунт не активен.'
        else:
            context['error'] = 'Неверный логин и/или пароль.'
            user_form = UserForm()
            context['user_form'] = user_form
            context['btn_title'] = 'Регистрация'
            context['url_btn'] = reverse('registration:user_register')
            context['title_page'] = 'Авторизация'
            return render(request, 'registration_app/login.html', context)
    else:
        user_form = UserForm()
        context['user_form'] = user_form
        context['btn_title'] = 'Регистрация'
        context['url_btn'] = reverse('registration:user_register')
        context['title_page'] = 'Авторизация'
        return render(request, 'registration_app/login.html', context)


def user_register(request):
    context = {}
    if request.method == 'POST':
        user_form = UserForm(request.POST or None)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            login(request, user)
            return HttpResponseRedirect(reverse('registration:doctors'))
        else:
            context['error'] = 'Пользователь с таким логином уже существует.'
            user_form = UserForm()
            context['user_form'] = user_form
            context['btn_title'] = 'Авторизация'
            context['url_btn'] = reverse('registration:user_login')
            context['title_page'] = 'Регистрация'
            return render(request, 'registration_app/register.html', context)
    else:
        user_form = UserForm()
        context['user_form'] = user_form
        context['btn_title'] = 'Авторизация'
        context['url_btn'] = reverse('registration:user_login')
        context['title_page'] = 'Регистрация'
        return render(request, 'registration_app/register.html', context)


def user_logout(request):
    logout(request)
    return redirect('registration:user_login')

med_registration/med_registration_project/templates/registration_app/base.html
{% load staticfiles %}
<!--DOCTYPE html-->
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <!--link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"-->
</head>

<body class="">
  <nav class="navbar navbar-expand-md text-center navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" {% if user.is_authenticated %}href="{% url 'registration:doctors' %}"{% else %}href="{% url 'registration:user_login' %}"{% endif %}>Поликлинника</a>
      <div class="text-center justify-content-center" id="navbar2SupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item active">
              <span class="nav-link">{% if user.is_authenticated %}{{ user.last_name }}{% endif %}</span>
          </li>
          <li class="nav-item active">
              <a class="nav-link btn btn-outline-primary" href="{{ url_btn }}">{{ btn_title }}</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
    <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-center text-primary">{{ title_page }}</h1>
        </div>
        {% if error %}
        <div class="col-md-12">
          <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
            <h4 class="alert-heading">Ошибка!</h4>
            <p>{{ error }}</p>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
  {% block content %}
  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>

</html>

med_registration/med_registration_project/templates/registration_app/doctors.html
{% extends 'registration_app/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="py-5 text-center">
    <div class="container">
      <div class="row">
        <!--Начало цикла-->
        {% for spec in specialty %}
        <div class="col-md-4">
          <div class="card my-1">
            <div class="card-block text-center">
              <h1 class="card-title">{{ spec.title }}</h1>
            </div>
            <!--Начало подцикла-->
            <ul class="list-group list-group-flush">
              {% for doctor in doctors %}
              {% if spec.id == doctor.specialty_id %}
              <li class="list-group-item"><i class="fa fa-fw fa-user-md" aria-hidden="false"></i>
                <a class="card-link" href="{% url 'registration:schedule' doctor.id %}">{{ doctor.full_name }}</a>
              </li>
              {% endif %}
              {% endfor %}
            </ul>
            <!--Конец подцикла-->
          </div>
        </div>
        {% endfor %}
        <!--Конец цикла-->
      </div>
    </div>
  </div>
{% endblock %}

med_registration/med_registration_project/templates/registration_app/doctors_list.html
{% extends 'registration_app/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="py-5 text-center">
    <div class="container">
      <div class="row">
        <!--Начало цикла-->
        {% for spec in specialty %}
        <div class="col-md-4">
          <div class="card my-1">
            <div class="card-block text-center">
              <h1 class="card-title">{{ spec.title }}</h1>
            </div>
            <!--Начало подцикла-->
            <ul class="list-group list-group-flush">
              {% for doctor in doctors %}
              {% if spec.id == doctor.specialty_id %}
              <li class="list-group-item"><i class="fa fa-fw fa-user-md"></i>
                <a class="card-link" href="{{ doctor.id }}">{{ doctor.full_name }}</a>
              </li>
              {% endif %}
              {% endfor %}
            </ul>
            <!--Конец подцикла-->
          </div>
        </div>
        {% endfor %}
        <!--Конец цикла-->
      </div>
    </div>
  </div>
{% endblock %}

med_registration/med_registration_project/templates/registration_app/login.html
{% extends 'registration_app/base.html' %}
{% load staticfiles %}


{% block content %}
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form class="" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <div class="form-group"> <label>Логин</label>
              {{ user_form.username }}
            </div>
            <div class="form-group"> <label>Пароль</label>
              {{ user_form.password }}
            </div>
            <input class="btn btn-primary" value="Войти" type="submit">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

med_registration/med_registration_project/templates/registration_app/record.html
{% extends 'registration_app/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="col-md-12">
            <img src="https://pingendo.com/assets/photos/user_placeholder.png" class="d-block mx-auto rounded-circle img-fluid my-3">
            <h3 class="text-center">{{ doctor.full_name }}</h3>
            <p class="text-center">{{ doctor.specialty }}</p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="py-5 section">
            <div class="container">
              <div class="row">
                <div class="col-md-12">
                  <p class="lead">Клиент: {{ client }}</p>
                  <p class="lead">Дата: {{ record_date }}</p>
                  <p class="lead">Время: {{ record_time }}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

med_registration/med_registration_project/templates/registration_app/record_list.html
{% extends 'registration_app/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="col-md-12">
            <img src="https://pingendo.com/assets/photos/user_placeholder.png" class="d-block mx-auto rounded-circle img-fluid my-3">
            <h3 class="text-center">{{ doctor.full_name }}</h3>
            <p class="text-center">{{ doctor.specialty }}</p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="py-5 section">
            <div class="container">
              <div class="row">
                <div class="col-md-12">
                  <p class="lead">Клиент: {{ client }}</p>
                  <p class="lead">Дата: {{ record_date }}</p>
                  <p class="lead">Время: {{ record_time }}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

med_registration/med_registration_project/templates/registration_app/register.html
{% extends 'registration_app/base.html' %}
{% load staticfiles %}


{% block content %}
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form class="" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <div class="form-group"> <label>Имя</label>
              {{ user_form.first_name }}
            </div>
            <div class="form-group"> <label>Фамилия</label>
              {{ user_form.last_name }}
            </div>
            <div class="form-group"> <label>Логин</label>
              {{ user_form.username }}
            </div>
            <div class="form-group"> <label>Пароль</label>
              {{ user_form.password }}
            </div>
            <input class="btn btn-primary" type="submit" value="Зарегистрироваться">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

med_registration/med_registration_project/templates/registration_app/schedule.html
{% extends 'registration_app/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="py-5  section">
    <div class="container">
      <div class="row">
        <div class="col-md-6 text-center">
          <img src="https://pingendo.com/assets/photos/user_placeholder.png" class="d-block mx-auto rounded-circle img-fluid my-3">
          <h3 class="text-center">{{ doctor.full_name }}</h3>
          <p class="text-center">{{ doctor.specialty }}</p>
        </div>
        <div class="col-md-6 text-left">
          {% for work_day in work_dates %}
          <div class="btn-group p-1">
            <button class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown"> {{ work_day|date:'d.m.Y' }} </button>
            <div class="dropdown-menu">
              {% for key, value in dates_dict.items %}
              {% if key == work_day %}
              {% for work_time in value %}
              <a class="dropdown-item" href="{% url 'registration:record_list' id=doctor.id year=work_day|date:'Y' month=work_day|date:'m' day=work_day|date:'d' hour=work_time %}">{{ work_time }}:00</a>
              {% endfor %}
              {% endif %}
              {% endfor %}
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}